import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// Import Wrapper yang baru kita buat
import GoogleAuthProviderWrapper from "@/components/GoogleAuthProviderWrapper"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Workify HRIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Kita bungkus children dengan Provider Google */}
        <GoogleAuthProviderWrapper>
            {children}
        </GoogleAuthProviderWrapper>
      </body>
    </html>
  );
}